const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];

const signals = [
  {type:'买入', cls:'buy', code:'600519', name:'贵州茅台', price:'¥ 1,486.00', change:'+2.14%', changeCls:'positive', strategy:'趋势动量 · 进取版', strength:5, time:'15:05:12'},
  {type:'买入', cls:'buy', code:'300750', name:'宁德时代', price:'¥ 218.65', change:'+1.76%', changeCls:'positive', strategy:'趋势动量 · 进取版', strength:4, time:'15:05:12'},
  {type:'卖出', cls:'sell', code:'601318', name:'中国平安', price:'¥ 43.82', change:'-1.08%', changeCls:'negative', strategy:'低波红利 · 稳健版', strength:4, time:'15:05:10'},
  {type:'买入', cls:'buy', code:'000858', name:'五粮液', price:'¥ 128.20', change:'+0.62%', changeCls:'positive', strategy:'趋势动量 · 进取版', strength:3, time:'15:05:08'},
  {type:'卖出', cls:'sell', code:'600036', name:'招商银行', price:'¥ 39.15', change:'-0.46%', changeCls:'negative', strategy:'低波红利 · 稳健版', strength:3, time:'15:05:05'},
  {type:'观察', cls:'watch', code:'002594', name:'比亚迪', price:'¥ 276.40', change:'+0.18%', changeCls:'positive', strategy:'趋势动量 · 进取版', strength:2, time:'15:05:02'}
];
const stocks = [
  ['600519','贵州茅台','食品饮料','¥ 1,486.00','+2.14%','上行','8.4%'],['300750','宁德时代','电力设备','¥ 218.65','+1.76%','上行','7.8%'],['000858','五粮液','食品饮料','¥ 128.20','+0.62%','上行','6.7%'],['601318','中国平安','非银金融','¥ 43.82','-1.08%','震荡','5.9%'],['600036','招商银行','银行','¥ 39.15','-0.46%','震荡','5.2%'],['002594','比亚迪','汽车','¥ 276.40','+0.18%','上行','4.8%'],['601888','中国中免','商贸零售','¥ 88.26','+1.42%','上行','4.3%'],['600276','恒瑞医药','医药生物','¥ 47.63','-0.24%','震荡','3.9%']
];
const trades = [['2025-08-18','600519 贵州茅台','买入','¥ 1,454.00','100','¥ 145,400','—'],['2025-08-15','601318 中国平安','卖出','¥ 44.30','1,800','¥ 79,740','+¥ 2,214'],['2025-08-12','300750 宁德时代','买入','¥ 212.80','600','¥ 127,680','—'],['2025-08-08','000858 五粮液','买入','¥ 125.10','700','¥ 87,570','—'],['2025-08-05','600036 招商银行','卖出','¥ 39.42','2,000','¥ 78,840','+¥ 1,080'],['2025-07-30','601888 中国中免','卖出','¥ 85.16','900','¥ 76,644','-¥ 1,350']];

let liveSignals = [];
let lastBacktest = null;
let universePage = 1;
let universeTotal = 0;
const fallbackCodes = ['600519','300750','000858','601318','600036','002594'];
function getWatchlist(){ try{return JSON.parse(localStorage.getItem('quantpilot-watchlist')||'[]')}catch{return []} }
function saveWatchlist(items){localStorage.setItem('quantpilot-watchlist',JSON.stringify([...new Set(items)]));}
function renderWatchlist(){ const body=$('#watchlist-body'); if(!body)return; const codes=getWatchlist(); if(!codes.length){body.innerHTML='<tr><td colspan="7" class="loading-cell">策略池为空。请先进入“全部 A 股”，搜索股票并点击“加入策略池”。</td></tr>'; $('#watchlist-meta').textContent='策略池为空'; return;} body.innerHTML=codes.map(code=>`<tr data-watch-code="${code}"><td>${code}</td><td class="watch-name">加载中…</td><td class="watch-price">—</td><td class="watch-change">—</td><td class="watch-time">—</td><td><button class="text-btn open-stock-detail" data-code="${code}">查看数据</button></td><td><button class="text-btn remove-watch" data-code="${code}">移除</button></td></tr>`).join(''); $$('.remove-watch').forEach(button=>button.addEventListener('click',()=>{saveWatchlist(codes.filter(item=>item!==button.dataset.code));renderWatchlist();showToast(`${button.dataset.code} 已从策略池移除`,'策略池已更新')})); $$('.open-stock-detail').forEach(button=>button.addEventListener('click',()=>openStockDetail(button.dataset.code))); apiJson(`/api/quotes?codes=${codes.join(',')}`).then(payload=>{const map=new Map((payload.items||[]).map(row=>[row.code,row])); codes.forEach(code=>{const row=$(`[data-watch-code="${code}"]`);const quote=map.get(code);if(!row||!quote)return;$('.watch-name',row).textContent=quote.name;$('.watch-price',row).textContent=`¥ ${Number(quote.price).toFixed(2)}`;$('.watch-change',row).textContent=fmtPct(quote.change);$('.watch-change',row).className=`watch-change ${Number(quote.change)>=0?'positive':'negative'}`;$('.watch-time',row).textContent=formatQuoteTime(quote.time)});$('#watchlist-meta').textContent=`已选 ${codes.length} 只 · 腾讯实时同步 ${new Date().toLocaleTimeString('zh-CN')}`}).catch(error=>{$('#watchlist-meta').textContent=`实时同步失败：${error.message}`}); }
let detailState={code:'',rows:[],quote:null};let detailLimit=120;
function average(values,n){return values.slice(-n).reduce((sum,value)=>sum+value,0)/Math.min(n,values.length)}
function rsiValue(values,n=14){if(values.length<n+1)return null;let gain=0,loss=0;for(let i=values.length-n;i<values.length;i++){const d=values[i]-values[i-1];if(d>0)gain+=d;else loss-=d}return loss?100-100/(1+(gain/n)/(loss/n)):100}
function renderIndicators(){const rows=detailState.rows;if(!rows.length)return;const close=rows.map(r=>r.close),last=rows.at(-1),prev=rows.at(-2);const ma20=average(close,20),ma60=average(close,60),rsi=rsiValue(close);const ret=(n)=>close.length>n?(last.close/close.at(-n-1)-1)*100:null;let ema12=close[0],ema26=close[0],signal=0,macd=0;for(let i=1;i<close.length;i++){ema12=close[i]*(2/13)+ema12*(11/13);ema26=close[i]*(2/27)+ema26*(25/27);macd=ema12-ema26;signal=macd*(2/10)+signal*(8/10)}const vals=[['收盘价',`¥${last.close.toFixed(2)}`],['SMA 20',`¥${ma20.toFixed(2)}`],['SMA 60',`¥${ma60.toFixed(2)}`],['RSI 14',rsi===null?'数据不足':rsi.toFixed(2)],['MACD',macd.toFixed(3)],['MACD信号线',signal.toFixed(3)],['20日动量',ret(20)===null?'数据不足':fmtPct(ret(20))],['60日动量',ret(60)===null?'数据不足':fmtPct(ret(60))],['当日振幅',prev?fmtPct((last.high-last.low)/prev.close*100):'—'],['成交量',`${(last.volume||0).toLocaleString()} 手`]];$('#indicator-values').innerHTML=vals.map(([name,value])=>`<div><small>${name}</small><strong>${value}</strong></div>`).join('')}
function drawDetailChart(){const canvas=$('#detail-canvas');const rows=detailState.rows.slice(-detailLimit);if(!canvas||!rows.length)return;const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(360,rect.width),h=Math.max(280,rect.height);canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const left=55,right=12,top=14,priceBottom=h*.72,volTop=h*.77,bottom=h-22,prices=rows.flatMap(row=>[row.high,row.low]),min=Math.min(...prices),max=Math.max(...prices),range=max-min||1,slot=(w-left-right)/rows.length,body=Math.max(2,slot*.58);c.strokeStyle='rgba(111,137,165,.18)';c.fillStyle='#71869d';c.font='10px sans-serif';for(let i=0;i<5;i++){const y=top+i*(priceBottom-top)/4;c.beginPath();c.moveTo(left,y);c.lineTo(w-right,y);c.stroke();c.fillText((max-(max-min)*i/4).toFixed(2),3,y+3)}const py=v=>top+(max-v)/range*(priceBottom-top);const maxVol=Math.max(...rows.map(r=>r.volume||0),1);rows.forEach((r,i)=>{const x=left+(i+.5)*slot,up=r.close>=r.open;c.strokeStyle=up?'#42d6a1':'#f07888';c.fillStyle=c.strokeStyle;c.beginPath();c.moveTo(x,py(r.high));c.lineTo(x,py(r.low));c.stroke();const y=Math.min(py(r.open),py(r.close)),bh=Math.max(1,Math.abs(py(r.open)-py(r.close)));if(up)c.strokeRect(x-body/2,y,body,bh);else c.fillRect(x-body/2,y,body,bh);const vh=(r.volume||0)/maxVol*(bottom-volTop);c.globalAlpha=.55;c.fillRect(x-body/2,bottom-vh,body,vh);c.globalAlpha=1});const indicator=$('#detail-indicator').value;if(indicator!=='none'){const close=rows.map(r=>r.close);const line=(values,color)=>{c.beginPath();let started=false;values.forEach((v,i)=>{if(!Number.isFinite(v))return;const x=left+(i+.5)*slot,y=py(v);if(!started){c.moveTo(x,y);started=true}else c.lineTo(x,y)});c.strokeStyle=color;c.lineWidth=1.4;c.stroke()};if(indicator==='sma'){line(close.map((_,i)=>i>=19?average(close.slice(0,i+1),20):null),'#e9bc62');line(close.map((_,i)=>i>=59?average(close.slice(0,i+1),60):null),'#a78bfa')}if(indicator==='ema'){let value=close[0];line(close.map((v,i)=>{value=i?v*(2/21)+value*(19/21):v;return value}),'#e9bc62')}if(indicator==='boll'){const band=close.map((_,i)=>{if(i<19)return null;const part=close.slice(i-19,i+1),m=average(part,20),sd=Math.sqrt(part.reduce((a,v)=>a+(v-m)**2,0)/20);return m+2*sd});line(band,'#e9bc62')}}c.fillStyle='#71869d';c.fillText(rows[0].date,left,bottom+16);c.fillText(rows.at(-1).date,w-right-70,bottom+16)}
async function loadStockDetail(){const code=detailState.code;if(!code)return;const period=$('#detail-period').value,adjust=$('#detail-adjust').value;$('#detail-source').textContent='正在加载东方财富K线与腾讯快照…';$('#announcement-list').innerHTML='<div class="empty-state">正在获取公告…</div>';const [quoteResult,klineResult,annResult]=await Promise.allSettled([apiJson(`/api/quote?code=${code}`),apiJson(`/api/eastmoney/kline?code=${code}&period=${period}&adjust=${adjust}&limit=500`),apiJson(`/api/eastmoney/announcements?code=${code}`)]);if(quoteResult.status==='fulfilled'){detailState.quote=quoteResult.value;const q=detailState.quote;$('#detail-title').textContent=`${q.name}（${code}）`;$('#detail-quote-grid').innerHTML=[['最新价',`¥ ${Number(q.price).toFixed(2)}`,Number(q.change)>=0?'positive':'negative'],['涨跌幅',fmtPct(q.change),Number(q.change)>=0?'positive':'negative'],['最高 / 最低',`${q.high} / ${q.low}`, ''],['成交额',`${Number(q.turnoverWan||0).toLocaleString()} 万元`, ''],['换手率',q.turnoverRate==null?'—':`${q.turnoverRate}%`,''],['市盈率 / 市净率',`${q.pe??'—'} / ${q.pb??'—'}`,'']].map(x=>`<div class="panel"><small>${x[0]}</small><strong class="${x[2]}">${x[1]}</strong></div>`).join('');$('#detail-meta').textContent=`腾讯实时快照 ${formatQuoteTime(q.time)} · ${new Date().toLocaleString('zh-CN')}`}if(klineResult.status==='fulfilled'){detailState.rows=klineResult.value.rows||[];$('#detail-source').textContent=`东方财富${({'101':'日K','102':'周K','103':'月K','1':'1分钟','5':'5分钟','15':'15分钟','30':'30分钟','60':'60分钟'})[period]} · ${adjust==='1'?'前复权':adjust==='2'?'后复权':'不复权'} · ${detailState.rows.length} 根`;renderIndicators();drawDetailChart()}else $('#detail-source').textContent=`K线加载失败：${klineResult.reason.message}`;if(annResult.status==='fulfilled'){const items=annResult.value.items||[];$('#announcement-list').innerHTML=items.length?items.map(item=>`<a class="announcement-item" href="${item.url}" target="_blank" rel="noopener"><span>${item.category} · ${item.time}</span><strong>${item.title}</strong></a>`).join(''):'<div class="empty-state">暂无近期公告</div>'}else $('#announcement-list').innerHTML=`<div class="empty-state">公告暂时无法获取：${annResult.reason.message}</div>`}
function openStockDetail(code){detailState={code,rows:[],quote:null};navigate('stock-detail');loadStockDetail()}
async function renderOverview(){const codes=getWatchlist();$('#overview-watch-count').textContent=codes.length;let result=null;try{result=JSON.parse(localStorage.getItem('quantpilot-last-backtest')||'null')}catch{}if(result){$('#overview-equity').textContent=`¥ ${Number(result.finalValue).toLocaleString('zh-CN',{maximumFractionDigits:0})}`;$('#overview-return').textContent=fmtPct(result.totalReturn);$('#overview-return').className=`metric-value ${Number(result.totalReturn)>=0?'positive':'negative'}`;$('#overview-drawdown').textContent=fmtPct(result.maxDrawdown);$('#overview-equity-meta').textContent=`回测初始资金 ¥ ${Number(result.initial).toLocaleString('zh-CN')} · ${result.codes?.join(',')||''}`;$('#overview-return-meta').textContent=`${result.tradeCount} 笔成交 · ${new Date(result.updatedAt).toLocaleString('zh-CN')}`;drawResultChart(result,'equity-canvas')}else{['overview-equity','overview-return','overview-drawdown'].forEach(id=>$('#'+id).textContent='—');clearChart($('#equity-canvas'))}const list=$('#overview-watchlist');if(!codes.length){list.innerHTML='<div class="empty-state">策略池为空</div>'}else{list.innerHTML=codes.map(code=>`<div class="overview-watch-row" data-overview-code="${code}"><strong>${code}</strong><span>同步中…</span><b>—</b></div>`).join('');try{const data=await apiJson(`/api/quotes?codes=${codes.join(',')}`);for(const quote of data.items||[]){const row=$(`[data-overview-code="${quote.code}"]`);if(row)row.innerHTML=`<strong>${quote.name}</strong><span>${quote.code}</span><b class="${Number(quote.change)>=0?'positive':'negative'}">¥${Number(quote.price).toFixed(2)} ${fmtPct(quote.change)}</b>`}}catch(error){list.innerHTML=`<div class="empty-state">行情同步失败：${error.message}</div>`}}const strategies=savedStrategies();$('#overview-strategies').innerHTML=strategies.length?strategies.slice(0,4).map(item=>`<div class="overview-strategy-row"><strong>${item.name}</strong><span>${item.spec.entry.length} 入场条件 · ${item.spec.exit.length} 离场条件</span></div>`).join(''):'<div class="empty-state">还没有保存的个人策略</div>'}
async function apiJson(url){ const response=await fetch(url,{cache:'no-store'}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error||'行情接口暂不可用'); return payload; }
function fmtPct(value){ if(value===null||value===undefined||!Number.isFinite(Number(value))) return '--'; return `${Number(value)>=0?'+':''}${Number(value).toFixed(2)}%`; }
function setClock(){ const now=new Date(); const label=$('#today-label'); if(label) label.textContent=now.toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'long',hour:'2-digit',minute:'2-digit',second:'2-digit'}); const signalDate=$('#signal-date'); if(signalDate)signalDate.textContent=now.toLocaleDateString('zh-CN'); }
function formatQuoteTime(value){ const text=String(value||''); if(/^\d{14}$/.test(text)){ const d=new Date(`${text.slice(0,4)}-${text.slice(4,6)}-${text.slice(6,8)}T${text.slice(8,10)}:${text.slice(10,12)}:${text.slice(12,14)}+08:00`); if(!Number.isNaN(d.getTime())) return d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}); } return '时间未知'; }
function signalRow(s){ const type=s.signal||s.type||'观察'; const cls=type==='买入'?'buy':type==='卖出'?'sell':'watch'; return `<div class="signal-item"><span class="signal-type ${cls}">${type}</span><div><strong>${s.name}</strong><small>${s.code} · ${s.reason||s.strategy||'趋势评分 · 日线'}</small></div><div class="signal-price"><strong>¥ ${Number(s.price).toFixed(2)}</strong><small class="${Number(s.change)>=0?'positive':'negative'}">${fmtPct(s.change)} · ${Number(s.score||0)}分</small></div></div>`; }
function signalTableRow(s){ const type=s.signal||'观察'; const cls=type==='买入'?'buy':type==='卖出'?'sell':'watch'; const strength=Number(s.strength)||1; return `<tr data-search="${s.code} ${s.name} ${s.reason||''}"><td><span class="sig-pill ${cls}">${type}</span></td><td><strong>${s.name}</strong><small class="table-sub">${s.code}</small></td><td>¥ ${Number(s.price).toFixed(2)}</td><td class="${Number(s.change)>=0?'positive':'negative'}">${fmtPct(s.change)}</td><td><strong>${Number(s.score||0)} 分</strong><small class="table-sub">${s.reason||s.strategy||'趋势评分 · 日线'}</small></td><td><div class="signal-strength"><span class="strength-bars">${[1,2,3,4,5].map(i=>`<i class="${i<=strength?'on':''}"></i>`).join('')}</span><small>${strength>=4?'强':strength>=3?'中':'弱'}</small></div></td><td>${s.time||'刚刚'}</td><td><button class="text-btn copy-signal" data-code="${s.code}">复制</button></td></tr>`; }
function renderLiveSignals(items){ liveSignals=items; const overview=$('#overview-signals'); if(overview) overview.innerHTML=items.slice(0,4).map(signalRow).join('')||'<div class="empty-state">暂无真实信号</div>'; const body=$('#signal-body'); if(body){ body.innerHTML=items.map(signalTableRow).join('')||'<tr><td colspan="8">暂无真实信号</td></tr>'; $$('.copy-signal').forEach(b=>b.addEventListener('click',()=>{navigator.clipboard?.writeText(b.dataset.code);showToast(`${b.dataset.code} 已复制到剪贴板`,'信号已复制')})); } }
async function loadSignals(showError=false){ try { const watchlist=getWatchlist(); const query=watchlist.length?`?codes=${watchlist.join(',')}`:''; const payload=await apiJson(`/api/signals${query}`); renderLiveSignals(payload.items||[]); const t=payload.items?.[0]?.time; setMarketStatus(`趋势筛选 ${payload.items?.length||0} 只 · 腾讯行情 ${formatQuoteTime(t)}`); } catch(error){ if(showError)showToast(error.message,'实时信号暂不可用'); } }
function liveStockRow(s){ const change=Number(s.change); const watched=getWatchlist().includes(s.code); return `<tr><td class="code">${s.code}</td><td><strong>${s.name}</strong></td><td>${s.industry||'未分类'}</td><td>${s.price===null||s.price===undefined?'--':`¥ ${Number(s.price).toFixed(2)}`}</td><td class="${change>=0?'positive':'negative'}">${fmtPct(change)}</td><td><span class="trend-tag ${change>=0?'up':''}">${change>=0?'实时上行':'实时走弱'}</span></td><td>${s.turnoverRate==null?'--':`${Number(s.turnoverRate).toFixed(2)}%`}</td><td><button class="text-btn watch-stock" data-code="${s.code}">${watched?'已在策略池':'加入策略池'}</button></td></tr>`; }
async function loadUniverse(query=''){ const body=$('#stock-body'); if(!body)return; body.innerHTML='<tr><td colspan="8" class="loading-cell">正在加载 A 股目录与腾讯实时行情…</td></tr>'; try { const payload=await apiJson(`/api/universe?page=${universePage}&pageSize=50&live=1&query=${encodeURIComponent(query)}`); universeTotal=payload.total||0; body.innerHTML=(payload.items||[]).map(liveStockRow).join('')||'<tr><td colspan="8">没有匹配的股票</td></tr>'; const meta=$('#universe-meta'); if(meta)meta.textContent=`共 ${universeTotal.toLocaleString()} 只 A 股 · 当前页 ${payload.liveCount||0} 条腾讯实时快照${payload.liveError?' · 实时快照暂时不可用':''} · ${new Date().toLocaleTimeString('zh-CN')}`; $$('.watch-stock').forEach(button=>button.addEventListener('click',()=>{const list=getWatchlist(); const code=button.dataset.code; if(list.includes(code)){saveWatchlist(list.filter(item=>item!==code));button.textContent='加入策略池';showToast(`${code} 已从策略池移除`,'股票池已更新')}else{saveWatchlist([...list,code]);button.textContent='已在策略池';showToast(`${code} 已加入策略池`,'股票池已更新')}})); setMarketStatus(payload.liveError?'股票目录已加载，实时快照稍后重试':'腾讯行情已同步'); } catch(error){ body.innerHTML=`<tr><td colspan="8" class="loading-cell">股票目录加载失败：${error.message}<br><button class="btn ghost retry-universe" type="button">点击重试</button></td></tr>`; $('.retry-universe',body)?.addEventListener('click',()=>loadUniverse(query)); showToast(error.message,'股票目录暂不可用'); } }
function setMarketStatus(text){ const el=$('#market-status'); if(el)el.textContent=text; const sync=$('#last-sync-label'); if(sync)sync.textContent=`最近同步 · ${new Date().toLocaleTimeString('zh-CN')}`; const pulse=$('#market-pulse'); if(pulse)pulse.classList.add('live'); }

function showToast(text, title='操作完成'){ const toast=$('#toast'); toast.querySelector('strong').textContent=title; toast.querySelector('small').textContent=text; toast.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2800); }
function renderSignals(){
  const overview=$('#overview-signals'); if(overview) overview.innerHTML=signals.slice(0,4).map(s=>`<div class="signal-item"><span class="signal-type ${s.cls}">${s.type}</span><div><strong>${s.name}</strong><small>${s.code} · ${s.strategy.split(' · ')[0]}</small></div><div class="signal-price"><strong>${s.price}</strong><small class="${s.changeCls}">${s.change}</small></div></div>`).join('');
  const body=$('#signal-body'); if(body) body.innerHTML=signals.map(s=>`<tr data-search="${s.code} ${s.name}"><td><span class="sig-pill ${s.cls}">${s.type}</span></td><td><strong>${s.name}</strong><small class="table-sub">${s.code}</small></td><td>${s.price}</td><td class="${s.changeCls}">${s.change}</td><td>${s.strategy}</td><td><div class="signal-strength"><span class="strength-bars">${[1,2,3,4,5].map(i=>`<i class="${i<=s.strength?'on':''}"></i>`).join('')}</span><small>${s.strength>=4?'强':'中'}</small></div></td><td>${s.time}</td><td><button class="text-btn copy-signal" data-code="${s.code}">复制</button></td></tr>`).join('');
}
function renderStocks(query=''){ const body=$('#stock-body'); if(!body)return; const list=stocks.filter(s=>(s.join('')+'').includes(query)); body.innerHTML=list.map(s=>`<tr><td class="code">${s[0]}</td><td><strong>${s[1]}</strong></td><td>${s[2]}</td><td>${s[3]}</td><td class="${s[4].startsWith('+')?'positive':'negative'}">${s[4]}</td><td><span class="trend-tag ${s[5]==='上行'?'up':''}">${s[5]}</span></td><td>${s[6]}</td><td><button class="text-btn remove-stock">移除</button></td></tr>`).join(''); $$('.remove-stock').forEach(b=>b.addEventListener('click',e=>{e.target.closest('tr').remove();showToast('已从当前股票池移除','股票池已更新')})); }
function renderTrades(){ const body=$('#trade-body'); if(body)body.innerHTML=trades.map(t=>`<tr><td>${t[0]}</td><td><strong>${t[1].split(' ')[1]}</strong><small class="table-sub">${t[1].split(' ')[0]}</small></td><td><span class="trade-dir ${t[2]==='买入'?'buy':'sell'}">${t[2]}</span></td><td>${t[3]}</td><td>${t[4]}</td><td>${t[5]}</td><td class="${t[6].startsWith('+')?'positive':t[6].startsWith('-')?'negative':''}">${t[6]}</td></tr>`).join(''); }
function drawChart(canvas, variant='equity'){
  if(!canvas)return; const rect=canvas.getBoundingClientRect(), dpr=window.devicePixelRatio||1, w=Math.max(300,rect.width), h=Math.max(180,rect.height); canvas.width=w*dpr; canvas.height=h*dpr; const c=canvas.getContext('2d'); c.scale(dpr,dpr); c.clearRect(0,0,w,h);
  const pad={l:8,r:9,t:15,b:14}; const chartW=w-pad.l-pad.r, chartH=h-pad.t-pad.b;
  c.strokeStyle='rgba(111,137,165,.14)'; c.lineWidth=1; for(let i=0;i<5;i++){const y=pad.t+i*chartH/4;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke()}
  let main=[], bench=[]; for(let i=0;i<70;i++){const t=i/69; const base=variant==='backtest'?1+0.23*t:1+0.18*t; main.push(base + Math.sin(i*.23)*.035 + Math.sin(i*.07)*.055 + (i>47?(i-47)*.0014:0)); bench.push(1 + .065*t + Math.sin(i*.18)*.025 - Math.cos(i*.07)*.018)}
  const min=.88,max=1.34, x=i=>pad.l+i/(main.length-1)*chartW, y=v=>pad.t+(max-v)/(max-min)*chartH;
  function line(data,color,width,dash=[]){c.save();c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.beginPath();data.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.stroke();c.restore()}
  line(bench,'#53677f',1.3,[4,4]); line(main,'#8e7bf8',2.2);
  const last=main.length-1; c.fillStyle='#b2a3ff';c.beginPath();c.arc(x(last),y(main[last]),3.1,0,Math.PI*2);c.fill();
}
function drawAllCharts(){let latest=null;try{latest=JSON.parse(localStorage.getItem('quantpilot-last-backtest')||'null')}catch{}if(latest?.equity?.length)drawResultChart(latest,'equity-canvas',Number($('.period.active')?.dataset.days)||0);else{clearChart($('#equity-canvas'));const label=$('#overview-chart-meta');if(label)label.textContent='运行回测后显示真实净值';}if(lastBacktest?.equity?.length)drawResultChart(lastBacktest,'backtest-canvas');else clearChart($('#backtest-canvas'))}
function clearChart(canvas){if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.max(300,rect.width)*dpr;canvas.height=Math.max(180,rect.height)*dpr;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height)}
function drawResultChart(result,target='backtest-canvas',days=0){ const canvas=typeof target==='string'?$('#'+target):target; if(!canvas||!result?.equity?.length)return;let series=result.equity;if(days>0)series=series.slice(-days);const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=Math.max(300,rect.width),h=Math.max(180,rect.height);canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const values=series.map(row=>Number(row.value)).filter(Number.isFinite);if(!values.length)return;const min=Math.min(...values),max=Math.max(...values),pad=12;c.strokeStyle='rgba(111,137,165,.14)';c.lineWidth=1;for(let i=0;i<5;i++){const y=pad+i*(h-pad*2)/4;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}const x=i=>i/Math.max(1,values.length-1)*w,y=v=>pad+(max-v)/Math.max(.0001,max-min)*(h-pad*2);c.strokeStyle='#8e7cf8';c.lineWidth=2.2;c.beginPath();values.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.stroke();c.fillStyle='#b2a3ff';c.beginPath();c.arc(x(values.length-1),y(values.at(-1)),3,0,Math.PI*2);c.fill();if(target==='equity-canvas'){const label=$('#overview-chart-meta');if(label)label.textContent=`最近回测 · ${series[0]?.date||''} 至 ${series.at(-1)?.date||''} · ${result.codes?.join(',')||''}`;const axis=$('#overview-chart-axis');if(axis)axis.innerHTML=`<span>${series[0]?.date||''}</span><span>${series.at(-1)?.date||''}</span>`}}
function navigate(view){ $$('.page').forEach(p=>p.classList.add('hidden')); const target=$(`#view-${view}`); if(target)target.classList.remove('hidden'); $$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); const names={overview:'总览',strategies:'策略实验室',backtest:'回测中心',signals:'交易信号',universe:'全部 A 股',watchlist:'策略池',data:'数据管理',logs:'运行日志',settings:'偏好设置','stock-detail':'个股详情'}; $('#page-title').textContent=names[view]||'总览'; if(view==='overview'){setTimeout(drawAllCharts,30);renderOverview()}if(view==='backtest')setTimeout(drawAllCharts,30);if(view==='watchlist')setTimeout(renderWatchlist,30);if(view==='strategies')populateStrategies();if(view==='stock-detail')setTimeout(drawDetailChart,30); }
function openModal(){ $('#strategy-modal').classList.add('open'); setTimeout(()=>$('#new-name').focus(),100); }
function closeModal(){ $('#strategy-modal').classList.remove('open'); }
const INDICATORS=[['close','收盘价'],['open','开盘价'],['high','最高价'],['low','最低价'],['volume','成交量'],['sma','简单均线 SMA'],['ema','指数均线 EMA'],['rsi','RSI'],['macd','MACD'],['macdSignal','MACD信号线'],['momentum','N日动量 (%)'],['bollUpper','布林上轨'],['bollLower','布林下轨'],['atr','ATR'],['highest','N日最高价'],['lowest','N日最低价'],['breakoutHigh','前N日高点'],['breakoutLow','前N日低点'],['volumeSma','成交量均线']];
const OPERATORS=[['gt','大于'],['gte','大于等于'],['lt','小于'],['lte','小于等于'],['crossUp','上穿'],['crossDown','下穿'],['eq','等于']];
const PRESETS=[
 {id:'preset-ma',name:'双均线交叉',desc:'快线向上穿越慢线买入，向下穿越卖出',strategy:'trend',spec:{entry:[{left:{name:'sma',period:20},op:'crossUp',right:{type:'indicator',name:'sma',period:60}}],exit:[{left:{name:'sma',period:20},op:'crossDown',right:{type:'indicator',name:'sma',period:60}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-momentum',name:'时间序列动量',desc:'60日动量转正持有，动量转负离场',strategy:'trend',spec:{entry:[{left:{name:'momentum',period:60},op:'gt',right:{type:'value',value:0}}],exit:[{left:{name:'momentum',period:60},op:'lt',right:{type:'value',value:0}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-rsi',name:'RSI 超卖反转',desc:'RSI(14)低于30买入，回到55以上离场',strategy:'reversal',spec:{entry:[{left:{name:'rsi',period:14},op:'lt',right:{type:'value',value:30}}],exit:[{left:{name:'rsi',period:14},op:'gte',right:{type:'value',value:55}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-macd',name:'MACD 金叉',desc:'MACD线上穿信号线买入，下穿离场',strategy:'trend',spec:{entry:[{left:{name:'macd',period:12},op:'crossUp',right:{type:'indicator',name:'macdSignal',period:9}}],exit:[{left:{name:'macd',period:12},op:'crossDown',right:{type:'indicator',name:'macdSignal',period:9}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-breakout',name:'20日区间突破',desc:'收盘价突破前20日高点买入，跌破前10日低点卖出',strategy:'trend',spec:{entry:[{left:{name:'close'},op:'crossUp',right:{type:'indicator',name:'breakoutHigh',period:20}}],exit:[{left:{name:'close'},op:'crossDown',right:{type:'indicator',name:'breakoutLow',period:10}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-boll',name:'布林均值回归',desc:'触及布林下轨买入，回归20日均线离场',strategy:'reversal',spec:{entry:[{left:{name:'close'},op:'lt',right:{type:'indicator',name:'bollLower',period:20}}],exit:[{left:{name:'close'},op:'gte',right:{type:'indicator',name:'sma',period:20}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-trend-filter',name:'均线趋势过滤 + RSI',desc:'收盘在EMA50上且RSI低于45时买入，跌破EMA50离场',strategy:'trend',spec:{entry:[{left:{name:'close'},op:'gt',right:{type:'indicator',name:'ema',period:50}},{left:{name:'rsi',period:14},op:'lt',right:{type:'value',value:45}}],exit:[{left:{name:'close'},op:'lt',right:{type:'indicator',name:'ema',period:50}}],entryJoin:'all',exitJoin:'any'}},
 {id:'preset-vol-break',name:'放量突破',desc:'收盘突破前20日高点且成交量高于20日均量',strategy:'trend',spec:{entry:[{left:{name:'close'},op:'crossUp',right:{type:'indicator',name:'breakoutHigh',period:20}},{left:{name:'volume'},op:'gt',right:{type:'indicator',name:'volumeSma',period:20}}],exit:[{left:{name:'close'},op:'lt',right:{type:'indicator',name:'sma',period:20}}],entryJoin:'all',exitJoin:'any'}}
];
function savedStrategies(){try{return JSON.parse(localStorage.getItem('quantpilot-strategies')||'[]')}catch{return []}}
function saveStrategies(rows){localStorage.setItem('quantpilot-strategies',JSON.stringify(rows))}
function indicatorSelect(value='close',attr='data-indicator'){return `<select ${attr}>${INDICATORS.map(([key,label])=>`<option value="${key}" ${key===value?'selected':''}>${label}</option>`).join('')}</select>`}
function conditionMarkup(group,rule={left:{name:'close',period:20},op:'crossUp',right:{type:'indicator',name:'sma',period:20}}){const right=rule.right||{};return `<div class="builder-rule" data-group="${group}"><div class="builder-side">${indicatorSelect(rule.left?.name||'close','data-left')}<input type="number" data-left-period min="2" max="500" value="${rule.left?.period||20}" aria-label="左侧周期"></div><select data-operator>${OPERATORS.map(([op,label])=>`<option value="${op}" ${op===(rule.op||'gt')?'selected':''}>${label}</option>`).join('')}</select><div class="builder-side"><select data-right-type><option value="value" ${right.type!=='indicator'?'selected':''}>固定数值</option><option value="indicator" ${right.type==='indicator'?'selected':''}>另一个指标</option></select><input data-right-value type="number" step="any" value="${right.value??0}" ${right.type==='indicator'?'hidden':''}>${indicatorSelect(right.name||'sma','data-right-indicator')}<input type="number" data-right-period min="2" max="500" value="${right.period||20}" aria-label="右侧周期" ${right.type==='indicator'?'':'hidden'}></div><button type="button" class="remove-rule" aria-label="删除条件">移除</button></div>`}
function addRule(group,rule){const host=$(`#${group}-rules`);if(!host)return;host.insertAdjacentHTML('beforeend',conditionMarkup(group,rule));bindRule(host.lastElementChild)}
function bindRule(row){const toggle=()=>{const indicator=row.querySelector('[data-right-type]').value==='indicator';row.querySelector('[data-right-value]').hidden=indicator;row.querySelector('[data-right-indicator]').hidden=!indicator;row.querySelector('[data-right-period]').hidden=!indicator};row.querySelector('[data-right-type]').addEventListener('change',toggle);row.querySelector('.remove-rule').addEventListener('click',()=>row.remove());toggle()}
function collectRules(group){return $$('#'+group+'-rules .builder-rule').map(row=>{const left={name:row.querySelector('[data-left]').value,period:Number(row.querySelector('[data-left-period]').value)||20};const type=row.querySelector('[data-right-type]').value;const right=type==='indicator'?{type,name:row.querySelector('[data-right-indicator]').value,period:Number(row.querySelector('[data-right-period]').value)||20}:{type,value:Number(row.querySelector('[data-right-value]').value)};return {left,op:row.querySelector('[data-operator]').value,right}})}
function fillBuilder(strategy){$('#builder-name').value=strategy.name;$('#builder-description').value=strategy.desc||'';$('#entry-join').value=strategy.spec.entryJoin||'all';$('#exit-join').value=strategy.spec.exitJoin||'any';for(const group of ['entry','exit']){$(`#${group}-rules`).innerHTML='';(strategy.spec[group]||[]).forEach(rule=>addRule(group,rule))}$('#builder-status').textContent=`已载入：${strategy.name}`}
function updateBacktestOptions(){const select=$('#bt-strategy');if(!select)return;const selected=select.value;select.innerHTML='<option value="trend">趋势规则</option><option value="lowvol">低波动模板</option><option value="reversal">反转模板</option>'+PRESETS.map(item=>`<option value="${item.id}">${item.name}</option>`).join('')+savedStrategies().map(item=>`<option value="custom:${item.id}">${item.name}（自定义）</option>`).join('');if([...select.options].some(option=>option.value===selected))select.value=selected}
function populateStrategies(){const cards=$('#strategy-cards');if(!cards)return;const custom=savedStrategies().map(item=>({...item,custom:true}));const all=[...PRESETS,...custom];cards.innerHTML=all.map((s,index)=>`<article class="panel strategy-card"><div class="strategy-card-top"><div><h3>${s.name}</h3><p>${s.desc||'个人自定义规则，可继续调整并回测'}</p></div><span class="tag-running">${s.custom?'个人策略':'常用模板'}</span></div><div class="strategy-performance"><div><small>${(s.spec.entry||[]).length} 条入场 · ${(s.spec.exit||[]).length} 条离场</small><strong class="strategy-template-icon">${String(index+1).padStart(2,'0')}</strong></div><div class="strategy-spark">规则策略</div></div><div class="strategy-card-foot"><span>${s.custom?'保存在本地':'可编辑并复制'}</span><button class="open-card" data-strategy-id="${s.id}">载入编辑</button><button class="run-template" data-strategy-id="${s.id}">去回测 →</button></div></article>`).join('');updateBacktestOptions()}
async function runBacktest(){ const code=($('#bt-code')?.value||'600519').trim(); const codes=getWatchlist(); if(!/^\d{6}$/.test(code)){showToast('请输入 6 位股票代码','参数错误');return} const button=$('#run-backtest'); if(button){button.disabled=true;button.textContent='↻ 正在运行真实数据回测'} try { const selected=$('#bt-strategy')?.value||'trend'; const saved=savedStrategies(); const preset=PRESETS.find(item=>item.id===selected); const custom=selected.startsWith('custom:')?saved.find(item=>`custom:${item.id}`===selected):null; const strategy=preset?.strategy||custom?.strategy||(['lowvol','reversal'].includes(selected)?selected:'trend'); const spec=preset?.spec||custom?.spec||null; const params=new URLSearchParams({code,codes:codes.length>1?codes.join(','):code,strategy,initial:($('#bt-initial')?.value||'1000000').replaceAll(',',''),start:$('#bt-start')?.value||'',end:$('#bt-end')?.value||'',fast:$('#fast-input')?.value||'20',slow:$('#slow-input')?.value||'60',commission:$('#bt-commission')?.value||'0.025',stampTax:$('#bt-stamp')?.value||'0.05',slippage:$('#bt-slippage')?.value||'0.1',frequency:$('#bt-frequency')?.value||'daily',maxPosition:$('#bt-position')?.value||'95',stopLoss:$('#bt-stoploss')?.value||'0'});if(spec)params.set('spec',JSON.stringify(spec)); const result=await apiJson(`/api/backtest?${params}`); lastBacktest=result;localStorage.setItem('quantpilot-last-backtest',JSON.stringify({totalReturn:result.totalReturn,maxDrawdown:result.maxDrawdown,sharpe:result.sharpe,tradeCount:result.tradeCount,finalValue:result.finalValue,initial:result.initial,updatedAt:new Date().toISOString(),codes:result.codes||[code],equity:result.equity})); $('#bt-return').textContent=fmtPct(result.totalReturn); $('#bt-annual').textContent=fmtPct(result.annual); $('#bt-drawdown').textContent=fmtPct(result.maxDrawdown); $('#bt-sharpe').textContent=Number(result.sharpe||0).toFixed(2); $('#bt-trades').textContent=result.tradeCount; $('#bt-win').textContent=fmtPct(result.winRate); $('#bt-pf').textContent=Number(result.profitFactor||0).toFixed(2); $('#result-date').textContent=`${result.codes?.join(',')||code} · ${result.source} · ${new Date().toLocaleString('zh-CN')}`; renderBacktestTrades(result.trades||[],result.codes?.join(',')||code); showToast(`已使用 ${result.dataPoints} 个真实交易日完成计算`,'回测完成'); navigate('backtest'); setTimeout(()=>drawResultChart(result),50); } catch(error){showToast(error.message,'回测失败')} finally {if(button){button.disabled=false;button.textContent='▶ 使用真实日线运行'}} }
function renderBacktestTrades(items,code){ const body=$('#trade-body'); if(!body)return; body.innerHTML=items.slice().reverse().map(t=>`<tr><td>${t.date}</td><td><strong>${code}</strong><small class="table-sub">腾讯日线</small></td><td><span class="trade-dir ${t.side.startsWith('买')?'buy':'sell'}">${t.side}</span></td><td>¥ ${Number(t.price).toFixed(2)}</td><td>${t.qty}</td><td>¥ ${(Number(t.price)*Number(t.qty)).toFixed(2)}</td><td class="${Number(t.pnl)>=0?'positive':Number(t.pnl)<0?'negative':''}">${t.pnl==null?'—':`${Number(t.pnl)>=0?'+':''}¥ ${Number(t.pnl).toFixed(2)}`}</td></tr>`).join('')||'<tr><td colspan="7">该参数组合没有产生交易</td></tr>'; }
function download(filename,text,type='text/plain'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
document.addEventListener('DOMContentLoaded',()=>{
  populateStrategies();updateBacktestOptions();setClock();renderOverview();clearChart($('#equity-canvas'));clearChart($('#backtest-canvas'));loadSignals(true);addRule('entry');addRule('exit');
  $$('.nav-item').forEach(n=>n.addEventListener('click',()=>navigate(n.dataset.view)));
  $$('[data-view-link]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.viewLink)));
  $('#open-strategy-btn').addEventListener('click',()=>{navigate('strategies');$('#builder-name').focus()});$$('.close-modal').forEach(b=>b.addEventListener('click',closeModal));$('#strategy-modal')?.addEventListener('click',e=>{if(e.target.id==='strategy-modal')closeModal()});
  $('#run-backtest').addEventListener('click',runBacktest);$('#run-backtest-top').addEventListener('click',runBacktest);
  $('#bt-use-watchlist').addEventListener('click',()=>{const codes=getWatchlist();if(!codes.length){showToast('策略池为空，请先加入股票','没有可用标的');return}$('#bt-code').value=codes[0];showToast(`已载入 ${codes.length} 只策略池标的，运行时会按组合回测`,'策略池已载入')});
  $$('.period').forEach(b=>b.addEventListener('click',()=>{$$('.period').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawAllCharts()}));
  $('#signal-search').addEventListener('input',e=>$$('#signal-body tr').forEach(r=>r.style.display=r.dataset.search.toLowerCase().includes(e.target.value.toLowerCase())?'':'none'));
  $('#stock-search').addEventListener('input',e=>{universePage=1;clearTimeout(window.universeSearchTimer);window.universeSearchTimer=setTimeout(()=>loadUniverse(e.target.value),350)});
  $('#refresh-universe').addEventListener('click',()=>loadUniverse($('#stock-search').value)); $('#watchlist-back').addEventListener('click',()=>navigate('universe')); $('#watchlist-refresh').addEventListener('click',renderWatchlist); $('#bt-frequency').addEventListener('change',()=>showToast(`调仓频率：${$('#bt-frequency').selectedOptions[0].textContent}`,'回测参数')); $('#bt-position').addEventListener('change',()=>showToast('最大仓位已更新','风控参数')); $('#bt-stoploss').addEventListener('change',()=>showToast('止损参数已更新','风控参数'));
  $$('.add-rule').forEach(button=>button.addEventListener('click',()=>addRule(button.dataset.group)));$('#reset-builder').addEventListener('click',()=>{for(const group of ['entry','exit'])$(`#${group}-rules`).innerHTML='';$('#builder-name').value='我的自定义策略';$('#builder-description').value='';addRule('entry');addRule('exit')});$('#save-builder').addEventListener('click',()=>{const name=$('#builder-name').value.trim();const spec={entry:collectRules('entry'),exit:collectRules('exit'),entryJoin:$('#entry-join').value,exitJoin:$('#exit-join').value};if(!name||!spec.entry.length){showToast('策略名称和至少一条入场规则必填','无法保存');return}const rows=savedStrategies();const existing=rows.find(item=>item.name===name);const strategy={id:existing?.id||`custom-${Date.now()}`,name,desc:$('#builder-description').value.trim(),strategy:'trend',spec,updatedAt:new Date().toISOString()};saveStrategies([...rows.filter(item=>item.id!==strategy.id),strategy]);populateStrategies();$('#bt-strategy').value=`custom:${strategy.id}`;showToast(`“${name}”已保存，可在回测中心运行`,'自定义策略已保存')});
  $('#detail-back').addEventListener('click',()=>navigate('watchlist'));$('#detail-refresh').addEventListener('click',loadStockDetail);$('#detail-period').addEventListener('change',loadStockDetail);$('#detail-adjust').addEventListener('change',loadStockDetail);$('#detail-indicator').addEventListener('change',drawDetailChart);$('#refresh-announcements').addEventListener('click',async()=>{try{const data=await apiJson(`/api/eastmoney/announcements?code=${detailState.code}`);$('#announcement-list').innerHTML=data.items.length?data.items.map(item=>`<a class="announcement-item" href="${item.url}" target="_blank" rel="noopener"><span>${item.category} · ${item.time}</span><strong>${item.title}</strong></a>`).join(''):'<div class="empty-state">暂无近期公告</div>'}catch(error){showToast(error.message,'公告刷新失败')}});$$('.detail-range').forEach(button=>button.addEventListener('click',()=>{$$('.detail-range').forEach(item=>item.classList.toggle('active',item===button));detailLimit=Number(button.dataset.limit);drawDetailChart()}));
  $('#fast-input').addEventListener('input',e=>$('#fast-output').textContent=`${e.target.value} 日`);
  $('#slow-input').addEventListener('input',e=>$('#slow-output').textContent=`${e.target.value} 日`);
  $('#export-report').addEventListener('click',()=>download('quantpilot-backtest.csv','日期,方向,价格,数量,盈亏\n'+($$('#trade-body tr').map(row=>$$('td',row).map(cell=>cell.textContent.trim()).join(',')).join('\n')),'text/csv;charset=utf-8'));
  $('#download-signals').addEventListener('click',()=>download('quantpilot-signals-2025-08-18.csv','信号,代码,名称,最新价,涨跌幅,策略,时间\n'+signals.map(s=>`${s.type},${s.code},${s.name},${s.price},${s.change},${s.strategy},${s.time}`).join('\n'),'text/csv;charset=utf-8')); 
  $$('.copy-signal').forEach(b=>b.addEventListener('click',()=>{navigator.clipboard?.writeText(b.dataset.code);showToast(`${b.dataset.code} 已复制到剪贴板`,'信号已复制')}));
  $('#refresh-signals').addEventListener('click',()=>loadSignals(true));$('#import-data-btn').addEventListener('click',()=>showToast('请进入股票池搜索或导入 CSV 行情','数据导入'));$('#update-data').addEventListener('click',()=>{loadSignals(true);showToast('已请求最新腾讯行情','数据更新中')});$('#add-stock').addEventListener('click',()=>{navigate('universe');setTimeout(()=>$('#stock-search')?.focus(),80)});$('#clear-logs').addEventListener('click',()=>{ $$('.log-row').forEach(r=>r.remove());showToast('运行日志已清空','操作完成')});$('#save-settings').addEventListener('click',()=>showToast('偏好设置已保存','保存成功'));
  $$('.market-pill').forEach(b=>b.addEventListener('click',()=>loadSignals(true)));
  $$('.table-filter').forEach(button=>button.addEventListener('click',()=>{$$('.table-filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');const kind=button.textContent.trim();$$('#trade-body tr').forEach(row=>row.style.display=kind==='全部'||row.textContent.includes(kind)?'':'none')}));
  $$('.filter-tabs button').forEach(button=>button.addEventListener('click',()=>{$$('.filter-tabs button').forEach(x=>x.classList.remove('active'));button.classList.add('active');const kind=button.textContent.trim().split(' ')[0];if($('#signal-body'))$$('#signal-body tr').forEach(row=>row.style.display=kind==='全部'||row.textContent.includes(kind)?'':'none');if($('#strategy-cards'))$$('#strategy-cards .strategy-card').forEach(row=>row.style.display=kind==='全部'||row.textContent.includes(kind)?'':'none')}));
  $('#strategy-search').addEventListener('input',e=>$$('#strategy-cards .strategy-card').forEach(card=>card.style.display=card.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none'));
  $$('.notice>button').forEach(button=>button.addEventListener('click',()=>button.closest('.notice').remove()));
  $$('.rule-head button').forEach(button=>button.addEventListener('click',()=>showToast('条件编辑器下一步会支持更多指标和组合条件','条件已准备')));
  $$('.icon-btn,.help-btn').forEach(button=>button.addEventListener('click',()=>showToast('当前页面支持搜索、刷新和导出；更多功能正在接入','功能提示')));
  document.addEventListener('click',event=>{
    const card=event.target.closest('.strategy-card .open-card'); if(card){const strategy=PRESETS.find(item=>item.id===card.dataset.strategyId)||savedStrategies().find(item=>item.id===card.dataset.strategyId);if(strategy){fillBuilder(strategy);navigate('strategies');$('#builder-status').textContent=`正在编辑“${strategy.name}”；保存时创建或更新个人策略`;}return;}
    const run=event.target.closest('.strategy-card .run-template');if(run){const strategy=PRESETS.find(item=>item.id===run.dataset.strategyId)||savedStrategies().find(item=>item.id===run.dataset.strategyId);if(strategy){$('#bt-strategy').value=strategy.custom?`custom:${strategy.id}`:strategy.id;$('#bt-code').value=getWatchlist()[0]||'600519';navigate('backtest');setTimeout(runBacktest,100)}return;}
    const source=event.target.closest('.source-row .text-btn'); if(source){showToast('数据源当前由服务端统一管理','数据源配置');return;}
    const addSource=event.target.closest('.source-panel .btn'); if(addSource){showToast('当前已接入腾讯行情和交易所股票目录','数据源已就绪');return;}
    const more=event.target.closest('.more-btn'); if(more){showToast('图表工具栏已准备，选择时间区间可刷新图表','图表操作');return;}
    const strategyFilter=event.target.closest('.strategy-toolbar>.btn'); if(strategyFilter){showToast('策略筛选可通过上方状态标签和搜索使用','策略筛选');return;}
  });
  $$('.setting-row input').forEach(input=>input.addEventListener('change',()=>showToast(input.checked?'设置已启用':'设置已停用','偏好设置')));
  window.addEventListener('resize',drawAllCharts);
  window.setInterval(()=>{setClock();loadSignals(false);if(!$('#view-overview').classList.contains('hidden'))renderOverview()},30000);
  document.addEventListener('click',event=>{const nav=event.target.closest('.nav-item'); if(nav&&nav.dataset.view==='universe')setTimeout(()=>loadUniverse($('#stock-search')?.value||''),50)});
});






